# Generated by Django 5.1.2 on 2024-10-19 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False, verbose_name='session key')),
                ('session_data', models.TextField(verbose_name='session data')),
                ('expire_date', models.DateTimeField(db_index=True, verbose_name='expire date')),
                ('first_time', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Custom Session',
                'verbose_name_plural': 'Custom Sessions',
            },
        ),
    ]
